### ISSUE TITLE
MediUX set crashes script

### ISSUE THREAD

**Issue by 2bitERROR** [bbrown430/plex-poster-set-helper#23]
Went to download and apply Scream: The TV Series (2015) set from Parrillized (https://mediux.pro/sets/18246) resulting in the script crashing.

`Enter a ThePosterDB set (or user) or a MediUX set url: https://mediux.pro/sets/18246
Traceback (most recent call last):
  File "/Users/xxxx/plex poster set helper/plex-poster-set-helper.py", line 394, in <module>
    set_posters(user_input, tv, movies)
  File "/Users/xxxx/plex poster set helper/plex-poster-set-helper.py", line 178, in set_posters
    movieposters, showposters, collectionposters = scrape(url)
                                                   ^^^^^^^^^^^
  File "/Users/xxxx/plex poster set helper/plex-poster-set-helper.py", line 369, in scrape
    return scrape_mediux(soup)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/plex poster set helper/plex-poster-set-helper.py", line 278, in scrape_mediux
    data_dict = parse_string_to_dict(script.text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/plex poster set helper/plex-poster-set-helper.py", line 90, in parse_string_to_dict
    parsed_dict = json.loads(json_data)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 729 (char 728)`

**Comment by 123JackCole** [comment]
Another example of this https://mediux.pro/sets/13427. Was about to open an issue myself. Same error.

**Comment by 2bitERROR** [comment]
> Another example of this https://mediux.pro/sets/13427. Was about to open an issue myself. Same error.

And that one used to work cause I grabbed it with an earlier version of the script.

**Comment by bbrown430** [comment]
Swamped with finals this and next week but will tackle this when I find the time. Thanks for bringing this to my attention!

**Comment by bbrown430** [comment]
@DouwJacobs could you take a look at this? Got a reddit comment citing this issue again with https://mediux.pro/sets/15597

**Comment by bbrown430** [comment]
Not sure who I need to tag but @2bitERROR @123JackCole this should be fixed with the latest commit. It is fixed for those links you submitted in this issue at least!
